// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageBodyProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SimulatedTemperatureSensor
{

    /// <summary>Holder for reflection information generated from MessageBodyProto.proto</summary>
    public static partial class MessageBodyProtoReflection
    {

        #region Descriptor
        /// <summary>File descriptor for MessageBodyProto.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static MessageBodyProtoReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChZNZXNzYWdlQm9keVByb3RvLnByb3RvEhpTaW11bGF0ZWRUZW1wZXJhdHVy",
                  "ZVNlbnNvciKZAgoQTWVzc2FnZUJvZHlQcm90bxJFCgdtYWNoaW5lGAEgASgL",
                  "MjQuU2ltdWxhdGVkVGVtcGVyYXR1cmVTZW5zb3IuTWVzc2FnZUJvZHlQcm90",
                  "by5NYWNoaW5lEkUKB2FtYmllbnQYAiABKAsyNC5TaW11bGF0ZWRUZW1wZXJh",
                  "dHVyZVNlbnNvci5NZXNzYWdlQm9keVByb3RvLkFtYmllbnQSEwoLdGltZUNy",
                  "ZWF0ZWQYAyABKAkaMAoHQW1iaWVudBITCgt0ZW1wZXJhdHVyZRgBIAEoARIQ",
                  "CghodW1pZGl0eRgCIAEoAxowCgdNYWNoaW5lEhMKC3RlbXBlcmF0dXJlGAEg",
                  "ASgBEhAKCHByZXNzdXJlGAIgASgBYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SimulatedTemperatureSensor.MessageBodyProto), global::SimulatedTemperatureSensor.MessageBodyProto.Parser, new[]{ "Machine", "Ambient", "TimeCreated" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::SimulatedTemperatureSensor.MessageBodyProto.Types.Ambient), global::SimulatedTemperatureSensor.MessageBodyProto.Types.Ambient.Parser, new[]{ "Temperature", "Humidity" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SimulatedTemperatureSensor.MessageBodyProto.Types.Machine), global::SimulatedTemperatureSensor.MessageBodyProto.Types.Machine.Parser, new[]{ "Temperature", "Pressure" }, null, null, null)})
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class MessageBodyProto : pb::IMessage<MessageBodyProto>
    {
        private static readonly pb::MessageParser<MessageBodyProto> _parser = new pb::MessageParser<MessageBodyProto>(() => new MessageBodyProto());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MessageBodyProto> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::SimulatedTemperatureSensor.MessageBodyProtoReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MessageBodyProto()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MessageBodyProto(MessageBodyProto other) : this()
        {
            machine_ = other.machine_ != null ? other.machine_.Clone() : null;
            ambient_ = other.ambient_ != null ? other.ambient_.Clone() : null;
            timeCreated_ = other.timeCreated_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MessageBodyProto Clone()
        {
            return new MessageBodyProto(this);
        }

        /// <summary>Field number for the "machine" field.</summary>
        public const int MachineFieldNumber = 1;
        private global::SimulatedTemperatureSensor.MessageBodyProto.Types.Machine machine_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::SimulatedTemperatureSensor.MessageBodyProto.Types.Machine Machine
        {
            get { return machine_; }
            set
            {
                machine_ = value;
            }
        }

        /// <summary>Field number for the "ambient" field.</summary>
        public const int AmbientFieldNumber = 2;
        private global::SimulatedTemperatureSensor.MessageBodyProto.Types.Ambient ambient_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::SimulatedTemperatureSensor.MessageBodyProto.Types.Ambient Ambient
        {
            get { return ambient_; }
            set
            {
                ambient_ = value;
            }
        }

        /// <summary>Field number for the "timeCreated" field.</summary>
        public const int TimeCreatedFieldNumber = 3;
        private string timeCreated_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string TimeCreated
        {
            get { return timeCreated_; }
            set
            {
                timeCreated_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as MessageBodyProto);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MessageBodyProto other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(Machine, other.Machine)) return false;
            if (!object.Equals(Ambient, other.Ambient)) return false;
            if (TimeCreated != other.TimeCreated) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            if (machine_ != null) hash ^= Machine.GetHashCode();
            if (ambient_ != null) hash ^= Ambient.GetHashCode();
            if (TimeCreated.Length != 0) hash ^= TimeCreated.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            if (machine_ != null)
            {
                output.WriteRawTag(10);
                output.WriteMessage(Machine);
            }
            if (ambient_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(Ambient);
            }
            if (TimeCreated.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(TimeCreated);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            if (machine_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Machine);
            }
            if (ambient_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ambient);
            }
            if (TimeCreated.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(TimeCreated);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MessageBodyProto other)
        {
            if (other == null)
            {
                return;
            }
            if (other.machine_ != null)
            {
                if (machine_ == null)
                {
                    machine_ = new global::SimulatedTemperatureSensor.MessageBodyProto.Types.Machine();
                }
                Machine.MergeFrom(other.Machine);
            }
            if (other.ambient_ != null)
            {
                if (ambient_ == null)
                {
                    ambient_ = new global::SimulatedTemperatureSensor.MessageBodyProto.Types.Ambient();
                }
                Ambient.MergeFrom(other.Ambient);
            }
            if (other.TimeCreated.Length != 0)
            {
                TimeCreated = other.TimeCreated;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            if (machine_ == null)
                            {
                                machine_ = new global::SimulatedTemperatureSensor.MessageBodyProto.Types.Machine();
                            }
                            input.ReadMessage(machine_);
                            break;
                        }
                    case 18:
                        {
                            if (ambient_ == null)
                            {
                                ambient_ = new global::SimulatedTemperatureSensor.MessageBodyProto.Types.Ambient();
                            }
                            input.ReadMessage(ambient_);
                            break;
                        }
                    case 26:
                        {
                            TimeCreated = input.ReadString();
                            break;
                        }
                }
            }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the MessageBodyProto message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types
        {
            public sealed partial class Ambient : pb::IMessage<Ambient>
            {
                private static readonly pb::MessageParser<Ambient> _parser = new pb::MessageParser<Ambient>(() => new Ambient());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pb::MessageParser<Ambient> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pbr::MessageDescriptor Descriptor
                {
                    get { return global::SimulatedTemperatureSensor.MessageBodyProto.Descriptor.NestedTypes[0]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                pbr::MessageDescriptor pb::IMessage.Descriptor
                {
                    get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public Ambient()
                {
                    OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public Ambient(Ambient other) : this()
                {
                    temperature_ = other.temperature_;
                    humidity_ = other.humidity_;
                    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public Ambient Clone()
                {
                    return new Ambient(this);
                }

                /// <summary>Field number for the "temperature" field.</summary>
                public const int TemperatureFieldNumber = 1;
                private double temperature_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public double Temperature
                {
                    get { return temperature_; }
                    set
                    {
                        temperature_ = value;
                    }
                }

                /// <summary>Field number for the "humidity" field.</summary>
                public const int HumidityFieldNumber = 2;
                private long humidity_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public long Humidity
                {
                    get { return humidity_; }
                    set
                    {
                        humidity_ = value;
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override bool Equals(object other)
                {
                    return Equals(other as Ambient);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public bool Equals(Ambient other)
                {
                    if (ReferenceEquals(other, null))
                    {
                        return false;
                    }
                    if (ReferenceEquals(other, this))
                    {
                        return true;
                    }
                    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Temperature, other.Temperature)) return false;
                    if (Humidity != other.Humidity) return false;
                    return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override int GetHashCode()
                {
                    int hash = 1;
                    if (Temperature != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Temperature);
                    if (Humidity != 0L) hash ^= Humidity.GetHashCode();
                    if (_unknownFields != null)
                    {
                        hash ^= _unknownFields.GetHashCode();
                    }
                    return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override string ToString()
                {
                    return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void WriteTo(pb::CodedOutputStream output)
                {
                    if (Temperature != 0D)
                    {
                        output.WriteRawTag(9);
                        output.WriteDouble(Temperature);
                    }
                    if (Humidity != 0L)
                    {
                        output.WriteRawTag(16);
                        output.WriteInt64(Humidity);
                    }
                    if (_unknownFields != null)
                    {
                        _unknownFields.WriteTo(output);
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public int CalculateSize()
                {
                    int size = 0;
                    if (Temperature != 0D)
                    {
                        size += 1 + 8;
                    }
                    if (Humidity != 0L)
                    {
                        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Humidity);
                    }
                    if (_unknownFields != null)
                    {
                        size += _unknownFields.CalculateSize();
                    }
                    return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(Ambient other)
                {
                    if (other == null)
                    {
                        return;
                    }
                    if (other.Temperature != 0D)
                    {
                        Temperature = other.Temperature;
                    }
                    if (other.Humidity != 0L)
                    {
                        Humidity = other.Humidity;
                    }
                    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(pb::CodedInputStream input)
                {
                    uint tag;
                    while ((tag = input.ReadTag()) != 0)
                    {
                        switch (tag)
                        {
                            default:
                                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                                break;
                            case 9:
                                {
                                    Temperature = input.ReadDouble();
                                    break;
                                }
                            case 16:
                                {
                                    Humidity = input.ReadInt64();
                                    break;
                                }
                        }
                    }
                }

            }

            public sealed partial class Machine : pb::IMessage<Machine>
            {
                private static readonly pb::MessageParser<Machine> _parser = new pb::MessageParser<Machine>(() => new Machine());
                private pb::UnknownFieldSet _unknownFields;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pb::MessageParser<Machine> Parser { get { return _parser; } }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public static pbr::MessageDescriptor Descriptor
                {
                    get { return global::SimulatedTemperatureSensor.MessageBodyProto.Descriptor.NestedTypes[1]; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                pbr::MessageDescriptor pb::IMessage.Descriptor
                {
                    get { return Descriptor; }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public Machine()
                {
                    OnConstruction();
                }

                partial void OnConstruction();

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public Machine(Machine other) : this()
                {
                    temperature_ = other.temperature_;
                    pressure_ = other.pressure_;
                    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public Machine Clone()
                {
                    return new Machine(this);
                }

                /// <summary>Field number for the "temperature" field.</summary>
                public const int TemperatureFieldNumber = 1;
                private double temperature_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public double Temperature
                {
                    get { return temperature_; }
                    set
                    {
                        temperature_ = value;
                    }
                }

                /// <summary>Field number for the "pressure" field.</summary>
                public const int PressureFieldNumber = 2;
                private double pressure_;
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public double Pressure
                {
                    get { return pressure_; }
                    set
                    {
                        pressure_ = value;
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override bool Equals(object other)
                {
                    return Equals(other as Machine);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public bool Equals(Machine other)
                {
                    if (ReferenceEquals(other, null))
                    {
                        return false;
                    }
                    if (ReferenceEquals(other, this))
                    {
                        return true;
                    }
                    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Temperature, other.Temperature)) return false;
                    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Pressure, other.Pressure)) return false;
                    return Equals(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override int GetHashCode()
                {
                    int hash = 1;
                    if (Temperature != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Temperature);
                    if (Pressure != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Pressure);
                    if (_unknownFields != null)
                    {
                        hash ^= _unknownFields.GetHashCode();
                    }
                    return hash;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public override string ToString()
                {
                    return pb::JsonFormatter.ToDiagnosticString(this);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void WriteTo(pb::CodedOutputStream output)
                {
                    if (Temperature != 0D)
                    {
                        output.WriteRawTag(9);
                        output.WriteDouble(Temperature);
                    }
                    if (Pressure != 0D)
                    {
                        output.WriteRawTag(17);
                        output.WriteDouble(Pressure);
                    }
                    if (_unknownFields != null)
                    {
                        _unknownFields.WriteTo(output);
                    }
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public int CalculateSize()
                {
                    int size = 0;
                    if (Temperature != 0D)
                    {
                        size += 1 + 8;
                    }
                    if (Pressure != 0D)
                    {
                        size += 1 + 8;
                    }
                    if (_unknownFields != null)
                    {
                        size += _unknownFields.CalculateSize();
                    }
                    return size;
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(Machine other)
                {
                    if (other == null)
                    {
                        return;
                    }
                    if (other.Temperature != 0D)
                    {
                        Temperature = other.Temperature;
                    }
                    if (other.Pressure != 0D)
                    {
                        Pressure = other.Pressure;
                    }
                    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
                }

                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                public void MergeFrom(pb::CodedInputStream input)
                {
                    uint tag;
                    while ((tag = input.ReadTag()) != 0)
                    {
                        switch (tag)
                        {
                            default:
                                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                                break;
                            case 9:
                                {
                                    Temperature = input.ReadDouble();
                                    break;
                                }
                            case 17:
                                {
                                    Pressure = input.ReadDouble();
                                    break;
                                }
                        }
                    }
                }

            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
